using System;
using System.Collections.Generic;
using System.Text;

using UnityEngine;
using Flighter.Input;

using UnityKeyCode = UnityEngine.KeyCode;
using FlighterKeyCode = Flighter.Input.KeyCode;
using FlighterMouseButton = Flighter.Input.MouseButton;

namespace FlighterUnity
{
    public static class KeyCodeConversion
    {
        static readonly Dictionary<FlighterKeyCode, UnityKeyCode> keyFlighterToUnity
            = new Dictionary<FlighterKeyCode, UnityKeyCode>
            {
                { FlighterKeyCode.Backspace, UnityKeyCode.Backspace },
                { FlighterKeyCode.Delete, UnityKeyCode.Delete },
                { FlighterKeyCode.Tab, UnityKeyCode.Tab },
                { FlighterKeyCode.Clear, UnityKeyCode.Clear },
                { FlighterKeyCode.Return, UnityKeyCode.Return },
                { FlighterKeyCode.Pause, UnityKeyCode.Pause },
                { FlighterKeyCode.Escape, UnityKeyCode.Escape },
                { FlighterKeyCode.Space, UnityKeyCode.Space },
                { FlighterKeyCode.Keypad0, UnityKeyCode.Keypad0 },
                { FlighterKeyCode.Keypad1, UnityKeyCode.Keypad1 },
                { FlighterKeyCode.Keypad2, UnityKeyCode.Keypad2 },
                { FlighterKeyCode.Keypad3, UnityKeyCode.Keypad3 },
                { FlighterKeyCode.Keypad4, UnityKeyCode.Keypad4 },
                { FlighterKeyCode.Keypad5, UnityKeyCode.Keypad5 },
                { FlighterKeyCode.Keypad6, UnityKeyCode.Keypad6 },
                { FlighterKeyCode.Keypad7, UnityKeyCode.Keypad7 },
                { FlighterKeyCode.Keypad8, UnityKeyCode.Keypad8 },
                { FlighterKeyCode.Keypad9, UnityKeyCode.Keypad9 },
                { FlighterKeyCode.KeypadPeriod, UnityKeyCode.KeypadPeriod },
                { FlighterKeyCode.KeypadDivide, UnityKeyCode.KeypadDivide },
                { FlighterKeyCode.KeypadMultiply, UnityKeyCode.KeypadMultiply },
                { FlighterKeyCode.KeypadMinus, UnityKeyCode.KeypadMinus },
                { FlighterKeyCode.KeypadPlus, UnityKeyCode.KeypadPlus },
                { FlighterKeyCode.KeypadEnter, UnityKeyCode.KeypadEnter },
                { FlighterKeyCode.KeypadEquals, UnityKeyCode.KeypadEquals },
                { FlighterKeyCode.UpArrow, UnityKeyCode.UpArrow },
                { FlighterKeyCode.DownArrow, UnityKeyCode.DownArrow },
                { FlighterKeyCode.RightArrow, UnityKeyCode.RightArrow },
                { FlighterKeyCode.LeftArrow, UnityKeyCode.LeftArrow },
                { FlighterKeyCode.Insert, UnityKeyCode.Insert },
                { FlighterKeyCode.Home, UnityKeyCode.Home },
                { FlighterKeyCode.End, UnityKeyCode.End },
                { FlighterKeyCode.PageUp, UnityKeyCode.PageUp },
                { FlighterKeyCode.PageDown, UnityKeyCode.PageDown },
                { FlighterKeyCode.F1, UnityKeyCode.F1 },
                { FlighterKeyCode.F2, UnityKeyCode.F2 },
                { FlighterKeyCode.F3, UnityKeyCode.F3 },
                { FlighterKeyCode.F4, UnityKeyCode.F4 },
                { FlighterKeyCode.F5, UnityKeyCode.F5 },
                { FlighterKeyCode.F6, UnityKeyCode.F6 },
                { FlighterKeyCode.F7, UnityKeyCode.F7 },
                { FlighterKeyCode.F8, UnityKeyCode.F8 },
                { FlighterKeyCode.F9, UnityKeyCode.F9 },
                { FlighterKeyCode.F10, UnityKeyCode.F10 },
                { FlighterKeyCode.F11, UnityKeyCode.F11 },
                { FlighterKeyCode.F12, UnityKeyCode.F12 },
                { FlighterKeyCode.Alpha0, UnityKeyCode.Alpha0 },
                { FlighterKeyCode.Alpha1, UnityKeyCode.Alpha1 },
                { FlighterKeyCode.Alpha2, UnityKeyCode.Alpha2 },
                { FlighterKeyCode.Alpha3, UnityKeyCode.Alpha3 },
                { FlighterKeyCode.Alpha4, UnityKeyCode.Alpha4 },
                { FlighterKeyCode.Alpha5, UnityKeyCode.Alpha5 },
                { FlighterKeyCode.Alpha6, UnityKeyCode.Alpha6 },
                { FlighterKeyCode.Alpha7, UnityKeyCode.Alpha7 },
                { FlighterKeyCode.Alpha8, UnityKeyCode.Alpha8 },
                { FlighterKeyCode.Alpha9, UnityKeyCode.Alpha9 },
                { FlighterKeyCode.Exclaim, UnityKeyCode.Exclaim },
                { FlighterKeyCode.DoubleQuote, UnityKeyCode.DoubleQuote },
                { FlighterKeyCode.Hash, UnityKeyCode.Hash },
                { FlighterKeyCode.Dollar, UnityKeyCode.Dollar },
                { FlighterKeyCode.Ampersand, UnityKeyCode.Ampersand },
                { FlighterKeyCode.Quote, UnityKeyCode.Quote },
                { FlighterKeyCode.LeftParen, UnityKeyCode.LeftParen },
                { FlighterKeyCode.RightParen, UnityKeyCode.RightParen },
                { FlighterKeyCode.Asterisk, UnityKeyCode.Asterisk },
                { FlighterKeyCode.Plus, UnityKeyCode.Plus },
                { FlighterKeyCode.Comma, UnityKeyCode.Comma },
                { FlighterKeyCode.Minus, UnityKeyCode.Minus },
                { FlighterKeyCode.Period, UnityKeyCode.Period },
                { FlighterKeyCode.Slash, UnityKeyCode.Slash },
                { FlighterKeyCode.Colon, UnityKeyCode.Colon },
                { FlighterKeyCode.Semicolon, UnityKeyCode.Semicolon },
                { FlighterKeyCode.Less, UnityKeyCode.Less },
                { FlighterKeyCode.Equals, UnityKeyCode.Equals },
                { FlighterKeyCode.Greater, UnityKeyCode.Greater },
                { FlighterKeyCode.Question, UnityKeyCode.Question },
                { FlighterKeyCode.At, UnityKeyCode.At },
                { FlighterKeyCode.LeftBracket, UnityKeyCode.LeftBracket },
                { FlighterKeyCode.Backslash, UnityKeyCode.Backslash },
                { FlighterKeyCode.RightBracket, UnityKeyCode.RightBracket },
                { FlighterKeyCode.Caret, UnityKeyCode.Caret },
                { FlighterKeyCode.Underscore, UnityKeyCode.Underscore },
                { FlighterKeyCode.BackQuote, UnityKeyCode.BackQuote },
                { FlighterKeyCode.A, UnityKeyCode.A },
                { FlighterKeyCode.B, UnityKeyCode.B },
                { FlighterKeyCode.C, UnityKeyCode.C },
                { FlighterKeyCode.D, UnityKeyCode.D },
                { FlighterKeyCode.E, UnityKeyCode.E },
                { FlighterKeyCode.F, UnityKeyCode.F },
                { FlighterKeyCode.G, UnityKeyCode.G },
                { FlighterKeyCode.H, UnityKeyCode.H },
                { FlighterKeyCode.I, UnityKeyCode.I },
                { FlighterKeyCode.J, UnityKeyCode.J },
                { FlighterKeyCode.K, UnityKeyCode.K },
                { FlighterKeyCode.L, UnityKeyCode.L },
                { FlighterKeyCode.M, UnityKeyCode.M },
                { FlighterKeyCode.N, UnityKeyCode.N },
                { FlighterKeyCode.O, UnityKeyCode.O },
                { FlighterKeyCode.P, UnityKeyCode.P },
                { FlighterKeyCode.Q, UnityKeyCode.Q },
                { FlighterKeyCode.R, UnityKeyCode.R },
                { FlighterKeyCode.S, UnityKeyCode.S },
                { FlighterKeyCode.T, UnityKeyCode.T },
                { FlighterKeyCode.U, UnityKeyCode.U },
                { FlighterKeyCode.V, UnityKeyCode.V },
                { FlighterKeyCode.W, UnityKeyCode.W },
                { FlighterKeyCode.X, UnityKeyCode.X },
                { FlighterKeyCode.Y, UnityKeyCode.Y },
                { FlighterKeyCode.Z, UnityKeyCode.Z },
                { FlighterKeyCode.LeftCurlyBracket, UnityKeyCode.LeftCurlyBracket },
                { FlighterKeyCode.Pipe, UnityKeyCode.Pipe },
                { FlighterKeyCode.RightCurlyBracket, UnityKeyCode.RightCurlyBracket },
                { FlighterKeyCode.Tilde, UnityKeyCode.Tilde },
                { FlighterKeyCode.Numlock, UnityKeyCode.Numlock },
                { FlighterKeyCode.CapsLock, UnityKeyCode.CapsLock },
                { FlighterKeyCode.ScrollLock, UnityKeyCode.ScrollLock },
                { FlighterKeyCode.RightShift, UnityKeyCode.RightShift },
                { FlighterKeyCode.RightControl, UnityKeyCode.RightControl },
                { FlighterKeyCode.LeftControl, UnityKeyCode.LeftControl },
                { FlighterKeyCode.RightAlt, UnityKeyCode.RightAlt },
                { FlighterKeyCode.LeftAlt, UnityKeyCode.LeftAlt },
                { FlighterKeyCode.LeftCommand, UnityKeyCode.LeftCommand },
                { FlighterKeyCode.LeftApple, UnityKeyCode.LeftApple },
                { FlighterKeyCode.LeftWindows, UnityKeyCode.LeftWindows },
                { FlighterKeyCode.AltGr, UnityKeyCode.AltGr },
                { FlighterKeyCode.Help, UnityKeyCode.Help },
                { FlighterKeyCode.Print, UnityKeyCode.Print },
                { FlighterKeyCode.SysReq, UnityKeyCode.SysReq },
                { FlighterKeyCode.Break, UnityKeyCode.Break },
                { FlighterKeyCode.Menu, UnityKeyCode.Menu }
            };

        static readonly Dictionary<UnityKeyCode, FlighterKeyCode> keyUnityToFlighter
            = new Dictionary<UnityKeyCode, FlighterKeyCode>
            {
                { UnityKeyCode.Backspace, FlighterKeyCode.Backspace },
                { UnityKeyCode.Delete, FlighterKeyCode.Delete },
                { UnityKeyCode.Tab, FlighterKeyCode.Tab },
                { UnityKeyCode.Clear, FlighterKeyCode.Clear },
                { UnityKeyCode.Return, FlighterKeyCode.Return },
                { UnityKeyCode.Pause, FlighterKeyCode.Pause },
                { UnityKeyCode.Escape, FlighterKeyCode.Escape },
                { UnityKeyCode.Space, FlighterKeyCode.Space },
                { UnityKeyCode.Keypad0, FlighterKeyCode.Keypad0 },
                { UnityKeyCode.Keypad1, FlighterKeyCode.Keypad1 },
                { UnityKeyCode.Keypad2, FlighterKeyCode.Keypad2 },
                { UnityKeyCode.Keypad3, FlighterKeyCode.Keypad3 },
                { UnityKeyCode.Keypad4, FlighterKeyCode.Keypad4 },
                { UnityKeyCode.Keypad5, FlighterKeyCode.Keypad5 },
                { UnityKeyCode.Keypad6, FlighterKeyCode.Keypad6 },
                { UnityKeyCode.Keypad7, FlighterKeyCode.Keypad7 },
                { UnityKeyCode.Keypad8, FlighterKeyCode.Keypad8 },
                { UnityKeyCode.Keypad9, FlighterKeyCode.Keypad9 },
                { UnityKeyCode.KeypadPeriod, FlighterKeyCode.KeypadPeriod },
                { UnityKeyCode.KeypadDivide, FlighterKeyCode.KeypadDivide },
                { UnityKeyCode.KeypadMultiply, FlighterKeyCode.KeypadMultiply },
                { UnityKeyCode.KeypadMinus, FlighterKeyCode.KeypadMinus },
                { UnityKeyCode.KeypadPlus, FlighterKeyCode.KeypadPlus },
                { UnityKeyCode.KeypadEnter, FlighterKeyCode.KeypadEnter },
                { UnityKeyCode.KeypadEquals, FlighterKeyCode.KeypadEquals },
                { UnityKeyCode.UpArrow, FlighterKeyCode.UpArrow },
                { UnityKeyCode.DownArrow, FlighterKeyCode.DownArrow },
                { UnityKeyCode.RightArrow, FlighterKeyCode.RightArrow },
                { UnityKeyCode.LeftArrow, FlighterKeyCode.LeftArrow },
                { UnityKeyCode.Insert, FlighterKeyCode.Insert },
                { UnityKeyCode.Home, FlighterKeyCode.Home },
                { UnityKeyCode.End, FlighterKeyCode.End },
                { UnityKeyCode.PageUp, FlighterKeyCode.PageUp },
                { UnityKeyCode.PageDown, FlighterKeyCode.PageDown },
                { UnityKeyCode.F1, FlighterKeyCode.F1 },
                { UnityKeyCode.F2, FlighterKeyCode.F2 },
                { UnityKeyCode.F3, FlighterKeyCode.F3 },
                { UnityKeyCode.F4, FlighterKeyCode.F4 },
                { UnityKeyCode.F5, FlighterKeyCode.F5 },
                { UnityKeyCode.F6, FlighterKeyCode.F6 },
                { UnityKeyCode.F7, FlighterKeyCode.F7 },
                { UnityKeyCode.F8, FlighterKeyCode.F8 },
                { UnityKeyCode.F9, FlighterKeyCode.F9 },
                { UnityKeyCode.F10, FlighterKeyCode.F10 },
                { UnityKeyCode.F11, FlighterKeyCode.F11 },
                { UnityKeyCode.F12, FlighterKeyCode.F12 },
                { UnityKeyCode.Alpha0, FlighterKeyCode.Alpha0 },
                { UnityKeyCode.Alpha1, FlighterKeyCode.Alpha1 },
                { UnityKeyCode.Alpha2, FlighterKeyCode.Alpha2 },
                { UnityKeyCode.Alpha3, FlighterKeyCode.Alpha3 },
                { UnityKeyCode.Alpha4, FlighterKeyCode.Alpha4 },
                { UnityKeyCode.Alpha5, FlighterKeyCode.Alpha5 },
                { UnityKeyCode.Alpha6, FlighterKeyCode.Alpha6 },
                { UnityKeyCode.Alpha7, FlighterKeyCode.Alpha7 },
                { UnityKeyCode.Alpha8, FlighterKeyCode.Alpha8 },
                { UnityKeyCode.Alpha9, FlighterKeyCode.Alpha9 },
                { UnityKeyCode.Exclaim, FlighterKeyCode.Exclaim },
                { UnityKeyCode.DoubleQuote, FlighterKeyCode.DoubleQuote },
                { UnityKeyCode.Hash, FlighterKeyCode.Hash },
                { UnityKeyCode.Dollar, FlighterKeyCode.Dollar },
                { UnityKeyCode.Ampersand, FlighterKeyCode.Ampersand },
                { UnityKeyCode.Quote, FlighterKeyCode.Quote },
                { UnityKeyCode.LeftParen, FlighterKeyCode.LeftParen },
                { UnityKeyCode.RightParen, FlighterKeyCode.RightParen },
                { UnityKeyCode.Asterisk, FlighterKeyCode.Asterisk },
                { UnityKeyCode.Plus, FlighterKeyCode.Plus },
                { UnityKeyCode.Comma, FlighterKeyCode.Comma },
                { UnityKeyCode.Minus, FlighterKeyCode.Minus },
                { UnityKeyCode.Period, FlighterKeyCode.Period },
                { UnityKeyCode.Slash, FlighterKeyCode.Slash },
                { UnityKeyCode.Colon, FlighterKeyCode.Colon },
                { UnityKeyCode.Semicolon, FlighterKeyCode.Semicolon },
                { UnityKeyCode.Less, FlighterKeyCode.Less },
                { UnityKeyCode.Equals, FlighterKeyCode.Equals },
                { UnityKeyCode.Greater, FlighterKeyCode.Greater },
                { UnityKeyCode.Question, FlighterKeyCode.Question },
                { UnityKeyCode.At, FlighterKeyCode.At },
                { UnityKeyCode.LeftBracket, FlighterKeyCode.LeftBracket },
                { UnityKeyCode.Backslash, FlighterKeyCode.Backslash },
                { UnityKeyCode.RightBracket, FlighterKeyCode.RightBracket },
                { UnityKeyCode.Caret, FlighterKeyCode.Caret },
                { UnityKeyCode.Underscore, FlighterKeyCode.Underscore },
                { UnityKeyCode.BackQuote, FlighterKeyCode.BackQuote },
                { UnityKeyCode.A, FlighterKeyCode.A },
                { UnityKeyCode.B, FlighterKeyCode.B },
                { UnityKeyCode.C, FlighterKeyCode.C },
                { UnityKeyCode.D, FlighterKeyCode.D },
                { UnityKeyCode.E, FlighterKeyCode.E },
                { UnityKeyCode.F, FlighterKeyCode.F },
                { UnityKeyCode.G, FlighterKeyCode.G },
                { UnityKeyCode.H, FlighterKeyCode.H },
                { UnityKeyCode.I, FlighterKeyCode.I },
                { UnityKeyCode.J, FlighterKeyCode.J },
                { UnityKeyCode.K, FlighterKeyCode.K },
                { UnityKeyCode.L, FlighterKeyCode.L },
                { UnityKeyCode.M, FlighterKeyCode.M },
                { UnityKeyCode.N, FlighterKeyCode.N },
                { UnityKeyCode.O, FlighterKeyCode.O },
                { UnityKeyCode.P, FlighterKeyCode.P },
                { UnityKeyCode.Q, FlighterKeyCode.Q },
                { UnityKeyCode.R, FlighterKeyCode.R },
                { UnityKeyCode.S, FlighterKeyCode.S },
                { UnityKeyCode.T, FlighterKeyCode.T },
                { UnityKeyCode.U, FlighterKeyCode.U },
                { UnityKeyCode.V, FlighterKeyCode.V },
                { UnityKeyCode.W, FlighterKeyCode.W },
                { UnityKeyCode.X, FlighterKeyCode.X },
                { UnityKeyCode.Y, FlighterKeyCode.Y },
                { UnityKeyCode.Z, FlighterKeyCode.Z },
                { UnityKeyCode.LeftCurlyBracket, FlighterKeyCode.LeftCurlyBracket },
                { UnityKeyCode.Pipe, FlighterKeyCode.Pipe },
                { UnityKeyCode.RightCurlyBracket, FlighterKeyCode.RightCurlyBracket },
                { UnityKeyCode.Tilde, FlighterKeyCode.Tilde },
                { UnityKeyCode.Numlock, FlighterKeyCode.Numlock },
                { UnityKeyCode.CapsLock, FlighterKeyCode.CapsLock },
                { UnityKeyCode.ScrollLock, FlighterKeyCode.ScrollLock },
                { UnityKeyCode.RightShift, FlighterKeyCode.RightShift },
                { UnityKeyCode.RightControl, FlighterKeyCode.RightControl },
                { UnityKeyCode.LeftControl, FlighterKeyCode.LeftControl },
                { UnityKeyCode.RightAlt, FlighterKeyCode.RightAlt },
                { UnityKeyCode.LeftAlt, FlighterKeyCode.LeftAlt },
                { UnityKeyCode.LeftCommand, FlighterKeyCode.LeftCommand },
                { UnityKeyCode.LeftWindows, FlighterKeyCode.LeftWindows },
                { UnityKeyCode.AltGr, FlighterKeyCode.AltGr },
                { UnityKeyCode.Help, FlighterKeyCode.Help },
                { UnityKeyCode.Print, FlighterKeyCode.Print },
                { UnityKeyCode.SysReq, FlighterKeyCode.SysReq },
                { UnityKeyCode.Break, FlighterKeyCode.Break },
                { UnityKeyCode.Menu, FlighterKeyCode.Menu }
            };

        static readonly Dictionary<FlighterMouseButton, int> mouseFlighterToUnity
            = new Dictionary<FlighterMouseButton, int>
            {
                { FlighterMouseButton.Left, 0 },
                { FlighterMouseButton.Right, 1 },
                { FlighterMouseButton.Middle, 2 },
                { FlighterMouseButton.Mouse3, 3 },
                { FlighterMouseButton.Mouse4, 4 },
                { FlighterMouseButton.Mouse5, 5 }
            };

        static readonly Dictionary<int, FlighterMouseButton> mouseUnityToFlighter
            = new Dictionary<int, FlighterMouseButton>
            {
                { 0, FlighterMouseButton.Left },
                { 1, FlighterMouseButton.Right },
                { 2, FlighterMouseButton.Middle },
                { 3, FlighterMouseButton.Mouse3 },
                { 4, FlighterMouseButton.Mouse4 },
                { 5, FlighterMouseButton.Mouse5 }
            };

        public static FlighterKeyCode ToFlighter(this UnityKeyCode keyCode) => keyUnityToFlighter[keyCode];
        public static UnityKeyCode ToUnity(this FlighterKeyCode keyCode) => keyFlighterToUnity[keyCode];
        public static FlighterMouseButton UnityMouseButtonToFlighter(int mouseButton) => mouseUnityToFlighter[mouseButton];
        public static int ToUnity(this FlighterMouseButton mouseButton) => mouseFlighterToUnity[mouseButton];
    }
}
